// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { SearchOrganisationsComponent } from '@app/view/organisation/search-organisations.component';
import { SearchOrganisationsVarsForm } from '@app/view/organisation/search-organisations.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";
import { OrganisationEditorImplComponent } from '@app/components/organisation/organisation-editor-impl.component';

@Component({
  selector: 'app-search-organisations',
  templateUrl: './search-organisations.component.html',
  styleUrls: ['./search-organisations.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    LoaderComponent,
    OrganisationEditorImplComponent,
  ],
})
export class SearchOrganisationsImplComponent extends SearchOrganisationsComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: SearchOrganisationsVarsForm): SearchOrganisationsVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}