// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { UserController } from '@app/controller/user/user-controller';

@Injectable()
export class UserControllerImpl extends UserController {

    constructor() {
        super();
    }

}
