// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.roguesystems.zetaedrms.document;

import org.springframework.stereotype.Repository;

/**
 * @see Document
 */
@Repository("documentDao")
public class DocumentDaoImpl
    extends DocumentDaoBase
{
    
    public DocumentDaoImpl(
        DocumentRepository documentRepository
    ) {

        super(
            documentRepository
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toDocumentDTO(
        Document source,
        DocumentDTO target)
    {
        // TODO verify behavior of toDocumentDTO
        super.toDocumentDTO(source, target);
        // WARNING! No conversion for target.metadata (can't convert source.getMetadata():java.util.Map to java.util.Map<K, V>
        target.setMetadata(source.getMetadata());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DocumentDTO toDocumentDTO(final Document entity)
    {
        // TODO verify behavior of toDocumentDTO
        return super.toDocumentDTO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private Document loadDocumentFromDocumentDTO(DocumentDTO documentDTO)
    {
        if (documentDTO.getId() == null)
        {
            return  Document.Factory.newInstance();
        }
        else
        {
            return this.load(documentDTO.getId());
        }
    }

    /**
     * {@inheritDoc}
     */
    public Document documentDTOToEntity(DocumentDTO documentDTO)
    {
        // TODO verify behavior of documentDTOToEntity
        Document entity = this.loadDocumentFromDocumentDTO(documentDTO);
        this.documentDTOToEntity(documentDTO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void documentDTOToEntity(
        DocumentDTO source,
        Document target,
        boolean copyIfNull)
    {
        // TODO verify behavior of documentDTOToEntity
        super.documentDTOToEntity(source, target, copyIfNull);
        // No conversion for target.metadata (can't convert source.getMetadata():java.util.Map<K, V> to java.util.Map
        target.setMetadata(source.getMetadata());
    }
}