// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { AccessPointController } from '@app/controller/access/access-point-controller';

@Injectable()
export class AccessPointControllerImpl extends AccessPointController {

    constructor() {
        super();
    }

}
