logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO
      bw:
        co:
          roguesystems: DEBUG
server:
  port: ${PORT:8085}
  servlet:
    context-path: /
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: -1 # No file size limit
      max-request-size: -1  # No limit on request size
      location: ${java.io.tmpdir}
      file-size-threshold: 50MB
  thymeleaf:
    cache: false
  mvc:
    format:
      date: iso
      date-time: iso
      time: HH:mm:ss
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  liquibase:
    enabled: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${CLIENT_ID:zetaerdms-api}
            provider: keycloak
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: ${AUTH_URL:http://localhost:8970}/realms/${REALM:zetaerdms}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_URL:http://localhost:8970}/realms/${REALM:zetaerdms}
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      timeout: 100
management:
  endpoint:
    health:
      show-details: always
    metrics:
      access: READ_ONLY
    prometheus:
      access: READ_ONLY
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
      version: ${spring.application.version}
rate-limiting:
  tokens: ${RATE_LIMIT:2000}
minio:
    url: ${MINIO_URL:http://localhost:9000}
    access-key: ${MINIO_ACCESS_KEY:minio}
    secret-key: ${MINIO_SECRET_KEY:minio123}
    bucket-name: ${MINIO_BUCKET:zetaerdms}