// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { MetadataController } from '@app/controller/document/metadata/metadata-controller';

@Injectable()
export class MetadataControllerImpl extends MetadataController {

    constructor() {
        super();
    }

}
