// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { MetadataDTO } from '@app/model/bw/co/roguesystems/zetaedrms/document/metadata/metadata-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';
import { SearchObject } from '@app/model/search-object';

@Injectable({
  providedIn: 'root'
})
export class MetadataApi {
    
    protected path = '/metadata';

    private http = inject(HttpClient);

    public findById(id: string | any ): Observable<MetadataDTO | any> {

        return this.http.get<MetadataDTO | any>(this.path + `/id/${id}`);
    }

    public getAll(): Observable<MetadataDTO[] | any[]> {

        return this.http.get<MetadataDTO[] | any[]>(this.path + `/all`);
    }

    public getAllPaged(pageNumber: number | any , pageSize: number | any ): Observable<MetadataDTO | any> {

        return this.http.get<MetadataDTO | any>(this.path + `/all/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public pagedSearch(criteria: SearchObject<string> | any ): Observable<MetadataDTO | any> {

        return this.http.post<MetadataDTO | any>(this.path + `/search/paged`, criteria);
    }

    public remove(id: string | any ): Observable<boolean | any> {

        return this.http.delete<boolean | any>(this.path + `/id/${id}`);
    }

    public save(metadata: MetadataDTO | any ): Observable<MetadataDTO | any> {

        return this.http.post<MetadataDTO | any>(this.path, metadata);
    }

    public search(criteria: string | any ): Observable<MetadataDTO[] | any[]> {

        return this.http.get<MetadataDTO[] | any[]>(this.path + `/search?criteria=${criteria}`);
    }

}
