// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { AuthorisationController } from '@app/controller/authorisation/authorisation-controller';

@Injectable()
export class AuthorisationControllerImpl extends AuthorisationController {

    constructor() {
        super();
    }

}
