// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { OrganisationListDTO } from '@app/model/bw/co/roguesystems/zetaedrms/organisation/organisation-list-dto';
import { OrganisationDTO } from '@app/model/bw/co/roguesystems/zetaedrms/organisation/organisation-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';
import { SearchObject } from '@app/model/search-object';

@Injectable({
  providedIn: 'root'
})
export class OrganisationApi {
    
    protected path = '/organisation';

    private http = inject(HttpClient);

    public findById(id: string | any ): Observable<OrganisationDTO | any> {

        return this.http.get<OrganisationDTO | any>(this.path + `/id/${id}`);
    }

    public getAll(): Observable<OrganisationDTO[] | any[]> {

        return this.http.get<OrganisationDTO[] | any[]>(this.path + `/all`);
    }

    public getAllPaged(pageNumber: number | any , pageSize: number | any ): Observable<Page<OrganisationListDTO> | any> {

        return this.http.get<Page<OrganisationListDTO> | any>(this.path + `/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public pagedSearch(criteria: SearchObject<string> | any ): Observable<Page<OrganisationListDTO> | any> {

        return this.http.post<Page<OrganisationListDTO> | any>(this.path + `/search/paged`, criteria);
    }

    public remove(id: string | any ): Observable<boolean | any> {

        return this.http.delete<boolean | any>(this.path + `/id/${id}`);
    }

    public save(organisation: OrganisationDTO | any ): Observable<OrganisationDTO | any> {

        return this.http.post<OrganisationDTO | any>(this.path, organisation);
    }

    public search(criteria: SearchObject<string> | any ): Observable<OrganisationListDTO[] | any[]> {

        return this.http.post<OrganisationListDTO[] | any[]>(this.path + `/search`, criteria);
    }

}
