// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { DepartmentViewComponent } from '@app/view/organisation/department/department-view.component';
import { DepartmentViewVarsForm } from '@app/view/organisation/department/department-view.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";
import { DepartmentDetailsImplComponent } from '@app/components/organisation/department/department-details-impl.component';
import { DepartmentEditorImplComponent } from '@app/components/organisation/department/department-editor-impl.component';

@Component({
  selector: 'app-department-view',
  templateUrl: './department-view.component.html',
  styleUrls: ['./department-view.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    LoaderComponent,
    DepartmentDetailsImplComponent,
    DepartmentEditorImplComponent,
  ],
})
export class DepartmentViewImplComponent extends DepartmentViewComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: DepartmentViewVarsForm): DepartmentViewVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}