// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { SearchDepartmentsComponent } from '@app/view/organisation/department/search-departments.component';
import { SearchDepartmentsVarsForm } from '@app/view/organisation/department/search-departments.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";
import { DepartmentSearchImplComponent } from '@app/components/organisation/department/department-search-impl.component';
import { DepartmentEditorImplComponent } from '@app/components/organisation/department/department-editor-impl.component';

@Component({
  selector: 'app-search-departments',
  templateUrl: './search-departments.component.html',
  styleUrls: ['./search-departments.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    LoaderComponent,
    DepartmentSearchImplComponent,
    DepartmentEditorImplComponent,
  ],
})
export class SearchDepartmentsImplComponent extends SearchDepartmentsComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: SearchDepartmentsVarsForm): SearchDepartmentsVarsForm{
        return form;
    }

    doNgOnDestroy(): void {
    }
}
