// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { DepartmentController } from '@app/controller/organisation/department/department-controller';

@Injectable()
export class DepartmentControllerImpl extends DepartmentController {

    constructor() {
        super();
    }

}
