// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, effect, inject, signal } from '@angular/core';
import { EditAccessPointTypeComponent } from '@app/view/access/type/edit-access-point-type.component';
import { EditAccessPointTypeVarsForm } from '@app/view/access/type/edit-access-point-type.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";
import { AppEnvStore } from '@app/store/app-env.state';
import { AuthorisationApiStore } from '@app/store/bw/co/roguesystems/zetaedrms/authorisation/authorisation-api.store';
import { UrlTree } from '@angular/router';
import { CommonModule } from '@angular/common';

export enum EditAccessPointTypeRestrictions {
  DELETE_BUTTON = '/access/type/edit{button:delete}',
}

@Component({
  selector: 'app-edit-access-point-type',
  templateUrl: './edit-access-point-type.component.html',
  styleUrls: ['./edit-access-point-type.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    LoaderComponent,
  ],
})
export class EditAccessPointTypeImplComponent extends EditAccessPointTypeComponent {
  loadingById = false;
  deleting = false;

  private appState = inject(AppEnvStore);
  private authorisationApiStore = inject(AuthorisationApiStore);

  constructor() {
    super();
    this.accessPointTypeApiStore.reset();
    this.success = this.accessPointTypeApiStore.success;
    this.loading = this.accessPointTypeApiStore.loading;
    this.error = this.accessPointTypeApiStore.error;
    this.messages = this.accessPointTypeApiStore.messages;
    this.loaderMessage = this.accessPointTypeApiStore.loaderMessage;

    effect(() => {
      let accessPointType = this.accessPointTypeApiStore.data();

      if (accessPointType) {
        // this.accessPointTypeControl.patchValue(accessPointType);

        // this.accessPointType = accessPointType;
      }

      let restrictedItems = this.authorisationApiStore.dataList();

      if (restrictedItems) {
        restrictedItems.forEach((item) => {
          if (item === EditAccessPointTypeRestrictions.DELETE_BUTTON) {
            // this.deleteUnrestricted = signal(true);
          }
        });
      }

      if (this.success() && this.deleting) {
        this.router.navigate(['/access/type']);
      }
    });
  }

  override beforeOnInit(form: EditAccessPointTypeVarsForm): EditAccessPointTypeVarsForm {
    this.route.queryParams.subscribe((params: any) => {
      if (params.id) {
        this.accessPointTypeApiStore.findById(params);
      }
    });

    const tree: UrlTree = this.router.parseUrl(this.router.url);
    let cleanUrl = tree.root.children['primary']?.segments.map((it) => it.path).join('/') || '';

    this.authorisationApiStore.findRestrictedViewItems({
      url: encodeURIComponent(`/${cleanUrl}{`),
      roles: this.appState.realmRoles().map((role) => role.value),
    });

    return form;
  }

  doNgOnDestroy(): void {}

  override beforeEditAccessPointTypeSave(form: any): void {
    let data = this.editAccessPointTypeForm.value;
    this.accessPointTypeApiStore.save(data);
  }

  override beforeEditAccessPointTypeDelete(): void {
    if (confirm('Are you sure you want to delete this item?. This action cannot be undone.')) {
      this.deleting = true;
      let data = this.editAccessPointTypeForm.value.accessPointType;
      this.accessPointTypeApiStore.remove({ id: data.id });
    }
  }
}
