// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { AccessPointTypeController } from '@app/controller/access/type/access-point-type-controller';

@Injectable()
export class AccessPointTypeControllerImpl extends AccessPointTypeController {

    constructor() {
        super();
    }

}
