// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { DepartmentDTO } from '@app/model/bw/co/roguesystems/zetaedrms/organisation/department/department-dto';
import { DepartmentListDTO } from '@app/model/bw/co/roguesystems/zetaedrms/organisation/department/department-list-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';
import { SearchObject } from '@app/model/search-object';

@Injectable({
  providedIn: 'root'
})
export class DepartmentApi {
    
    protected path = '/organisation/department';

    private http = inject(HttpClient);

    public findById(id: string | any ): Observable<DepartmentDTO | any> {

        return this.http.get<DepartmentDTO | any>(this.path + `/id/${id}`);
    }

    public getAll(): Observable<DepartmentListDTO[] | any[]> {

        return this.http.get<DepartmentListDTO[] | any[]>(this.path + `/all`);
    }

    public getAllPaged(pageNumber: number | any , pageSize: number | any ): Observable<Page<DepartmentListDTO> | any> {

        return this.http.get<Page<DepartmentListDTO> | any>(this.path + `/page/${pageNumber}/size/${pageSize}?pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public getOrganisationDepartments(organisationId: string | any ): Observable<DepartmentListDTO[] | any[]> {

        return this.http.get<DepartmentListDTO[] | any[]>(this.path + `/organisationId/${organisationId}`);
    }

    public getPagedOrganisationDepartments(organisationId: string | any , pageNumber: number | any , pageSize: number | any ): Observable<Page<DepartmentListDTO> | any> {

        return this.http.get<Page<DepartmentListDTO> | any>(this.path + `/organisationId/${organisationId}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public pagedSearch(criteria: SearchObject<DepartmentListDTO> | any ): Observable<Page<DepartmentListDTO> | any> {

        return this.http.post<Page<DepartmentListDTO> | any>(this.path + `/search/paged`, criteria);
    }

    public remove(id: string | any ): Observable<boolean | any> {

        return this.http.delete<boolean | any>(this.path + `/id/${id}`);
    }

    public save(department: DepartmentDTO | any ): Observable<DepartmentDTO | any> {

        return this.http.post<DepartmentDTO | any>(this.path, department);
    }

    public search(criteria: SearchObject<DepartmentListDTO> | any ): Observable<DepartmentListDTO[] | any[]> {

        return this.http.post<DepartmentListDTO[] | any[]>(this.path + `/search`, criteria);
    }

}
